### ISSUE TITLE
Cannot run Tye with Dapr on WSL2

### ISSUE THREAD

**Issue by tungphuong** [dotnet/tye#795] opened 2020-11-16 09:51 UTC
When I use `tye run` on WSL2 (Ubuntu 20) with dapr, the system throws an exception 

> [16:36:32 ERR] Failed to launch process for service webapigatewayapp-dapr_1314e939-4
> System.ComponentModel.Win32Exception (2): No such file or directory
>    at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
>    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
>    at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, Action`1 onStop, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 113
>    at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass8_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 402

**But it is working well on Window with Powershell environment.**

**Comment by jkotalik** [comment] 2020-11-16 16:23
Do you have dapr installed installed in your wsl2 environment? Follow the linux instructions for installing dapr here: https://docs.dapr.io/getting-started/install-dapr/

**Comment by tungphuong** [comment] 2020-11-17 02:29
@jkotalik Yes, I installed in my WSL2 environment and also run the command "tye init". I tried many times but have still got the same error

**Comment by ssohans** [comment] 2020-11-25 15:47
Having same error when i use "tye run" on ubuntu 20.04

**Comment by jkotalik** [comment] 2020-11-25 17:53
I'll try to repro this and see what is going on.

**Comment by ssohans** [comment] 2020-11-25 17:57
> I'll try to repro this and see what is going on.

Thanks. I got error for this repo "[coolstore-microservices](https://github.com/vietnam-devs/coolstore-microservices)" when run with tye.

**Comment by slacksach** [comment] 2020-12-23 10:42
Having the same issue when running using ubuntu-20.04 image on Azure DevOps Pipelines. Same issue with ubuntu-18.04 image. Also reproduced locally via WSL2 using ubuntu2004

**Comment by jkotalik** [comment] 2021-01-11 23:08
Hm, I'm currently not hitting this when I tried to repro right now. One thing I did notice is that daprd when installed with sudo is installed in /root/.dapr/bin instead of ~/.dapr/bin. That is a small fix we can add.

Can you all:
1. Post the path to daprd for your WSL2 instance.
2. Try with the latest nightlies of tye (we will try to release a new version in the coming weeks). https://github.com/dotnet/tye/blob/master/docs/getting_started.md#working-with-ci-builds

**Comment by slacksach** [comment] 2021-01-12 09:33
Hi @jkotalik,

Will dig out the daprd path from WSL2, I'll run against one of the MS Azure DevOps Ubuntu agents to see where daprd is located.

**Comment by jkotalik** [comment] 2021-01-19 20:11
@slacksach any luck?

**Comment by slacksach** [comment] 2021-01-21 17:36
@jkotalik sorry for the delay,

dapr init output
![image](https://user-images.githubusercontent.com/75119677/105388932-24681d80-5c0f-11eb-8df2-e5e407055221.png)

**Comment by jkotalik** [comment] 2021-01-21 17:37
@slacksach can you try the latest release of tye and see if your issue are gone? I fixed one small issue with WSL2 + Dapr that should help here.

**Comment by slacksach** [comment] 2021-01-21 17:38
@jkotalik sure thing - Was this the fix? - https://github.com/dotnet/tye/pull/907/files

**Comment by jkotalik** [comment] 2021-01-21 17:39
Yep!

**Comment by slacksach** [comment] 2021-01-21 17:42
@jkotalik using the latest 0.7

`[17:41:21 ERR] Failed to launch process for service aggregator-api-dapr_58f8b17d-9
System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, Action`1 onStop, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 117
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass8_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 402
`

**Comment by slacksach** [comment] 2021-01-21 17:43
@jkotalik - No luck i'm afraid - ```
[17:41:21 ERR] Failed to launch process for service [REDACTED]
System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, Action`1 onStop, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 117
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass8_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 402

```

**Comment by slacksach** [comment] 2021-01-21 17:45
@jkotalik - No luck i'm afraid

```
[17:41:21 ERR] Failed to launch process for service [REDACTED]
System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, Action`1 onStop, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 117
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass8_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 402
```

Using tye `0.7.0-alpha.21070.7+eb3b50699b7a5f2d0997a5cc8c5185d056dde8ec
`

**Comment by jkotalik** [comment] 2021-01-21 17:47
What's do the logs from the dapr processes say? Like what command is it trying to run, and what happens when you run that command yourself on command line?

**Comment by slacksach** [comment] 2021-01-21 17:52
looks like it is a path issue, as daprd isn't added to the path so it isn't finding it.

**Comment by jkotalik** [comment] 2021-01-21 17:54
Oh, I see the issue now. Is it possible to install dapr not with sudo? We had a discussion about this, and decided not to automatically look for dapr in /root/.bin/dapr as we believed it wasn't a common scenario.

**Comment by slacksach** [comment] 2021-01-21 17:57
@jkotalik I think dapr will install without sudo, not sure why I used sudo, just tried it again and seemed to work all good.

Have tried with the latest pre-release 0.6 and it works like a charm.

**Comment by jkotalik** [comment] 2021-01-21 17:58
Awesome, going to close this then. Feel free to reopen if you have any issues.

**Closed by jkotalik** 2021-01-21 17:58 UTC
Labels: bug

**Comment by slacksach** [comment] 2021-01-22 15:51
@jkotalik seems locally with WSL2 all was well but running an Azure Devops Pipelines Ubuntu 2004

```
Loading Application Details...
Launching Tye Host...

An unhandled exception has occurred, how unseemly: 
System.ArgumentException: An item with the same key has already been added. Key: placement
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Microsoft.Tye.ApplicationBuilderExtensions.ToHostingApplication(ApplicationBuilder application) in /_/src/tye/ApplicationBuilderExtensions.cs:line 183
   at Microsoft.Tye.Program.<>c.<<CreateRunCommand>b__18_0>d.MoveNext() in /_/src/tye/Program.RunCommand.cs:line 125
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by thinhnotes** [comment] 2021-06-30 03:56
I had a same problem when used the gitpod

Step reproduce:
step 1: run git pod
- access on the browser with loged gitpod account by url 
- https://gitpod.io/#https://github.com/dotnet/tye/tree/main/samples/dapr/service-invocation

step 2: install dotnet core SDK
`wget https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
`
```
 sudo apt-get update; \
  sudo apt-get install -y apt-transport-https && \
  sudo apt-get update && \
  sudo apt-get install -y dotnet-sdk-5.0 && \
  sudo apt-get install -y dotnet-sdk-3.1
```
step 3: add nuget package source 
`
dotnet nuget add  source https://api.nuget.org/v3/index.json
`
 
step 4: Install tye 
- dotnet tool install -g Microsoft.Tye --version "0.8.0-*" --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json

step 5: Run tye on folder example 
 ```
cd samples/dapr/pub-sub
tye run -v Debug
 ```


The error bellow:
3:51:15 ERR] Failed to launch process for service orders-dapr_13a2846b-c
System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, Action`1 onStop, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 138
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass8_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 397
[03:51:15 ERR] Failed to launch process for service store-dapr_c73e43b1-3
System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, Action`1 onStop, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 138
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass8_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 397
[03:51:15 ERR] Failed to launch process for service products-dapr_0ed4fabe-0
System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, Action`1 onStop, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 138
   at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass8_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 397
[03:51:15 INF] Collecting docker logs for redis_8e7375b1-a.
[03:51:15 INF] products_544cec67-6 running on process id 12504 bound to http://localhost:32921, https://localhost:42113
[03:51:15 INF] Replica products_544cec67-6 is moving to a ready state
[03:51:15 INF] Selected process 12499.
[03:51:15 INF] Selected process 12500.
[03:51:15 INF] Listening for event pipe events for store_1853dbf2-e on process id 12499
[03:51:15 INF] Listening for event pipe events for orders_0c72985b-b on process id 12500
[03:51:15 ERR] docker run failed for placement with exit code 127: docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: close exec fds: open /proc/self/fd: no such file or directory: unknown.
