### ISSUE TITLE
An unhandled exception has occurred

### ISSUE THREAD

**Issue by nibro7778** [dotnet/tye#1150] opened 2021-08-18 03:05 UTC
### Describe the bug
When I run the `tye run` command I am getting the following error 

```
$ tye run
Loading Application Details...
An unhandled exception has occurred, how unseemly:
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.Tye.ProjectReader.EnumerateProjectsCore(FileInfo solutionFile)+MoveNext()
   at Microsoft.Tye.ConfigModel.ConfigFactory.FromSolution(FileInfo file) in /_/src/Microsoft.Tye.Core/ConfigModel/ConfigFactory.cs:line 66
   at Microsoft.Tye.ConfigModel.ConfigFactory.FromFile(FileInfo file) in /_/src/Microsoft.Tye.Core/ConfigModel/ConfigFactory.cs:line 33
   at Microsoft.Tye.ApplicationFactory.CreateAsync(OutputContext output, FileInfo source, ApplicationFactoryFilter filter) in /_/src/Microsoft.Tye.Core/ApplicationFactory.cs:line 27
   at Microsoft.Tye.Program.<>c.<<CreateRunCommand>b__10_0>d.MoveNext() in /_/src/tye/Program.RunCommand.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

### To Reproduce
Please find below the image with tye and dotnet version 

![6dw2A5SuBo](https://user-images.githubusercontent.com/16951150/129830163-5f64446f-3068-4803-8a43-530b1e8f6cdd.png)

### Further technical details

- `tye --version` = `0.4.0-alpha.20371.1+d7623120d66b85bfeda8ab69eb5ff792df6b7243` 
- `dotnet --version` = `6.0.100-preview.7.21379.14`
- `tye run -v debug` also return same output
- The platform (Windows)

**Comment by pratiksanglikar** [comment] 2021-08-19 19:50
@nibro7778 what type of application are you trying to run?
i.e. Console Application, ASP.Net Core web application, Blazor application, etc.?

**Comment by nibro7778** [comment] 2021-08-19 22:37
I am trying to run ASP.Net Core web application and resolved this issue by upgrading the version. Now i am running on following version

tye version
```
$ tye --version
0.9.0-alpha.21380.1+836b0baa8a0ed5d8ca3bebc27c7d4f6d0a7bdfd9
```

**Comment by pratiksanglikar** [comment] 2021-08-19 22:42
I am happy the issue is resolved for you, I am closing this issue for now, but please feel free to open another issue if you encounter any problems!
Happy coding! :)

**Closed by pratiksanglikar** 2021-08-19 22:42 UTC
Labels: bug
