### ISSUE TITLE
Locking exe/dll files creates interesting circular problem

### ISSUE THREAD

**Issue by dziedrius** [dotnet/tye#949] opened 2021-02-25 09:46 UTC
We have several .net apps and postgres database running in tye. Also we use Entity Framework migrations.
The way EF migrations work is you run this:
```
dotnet ef database update
```
and it compiles the stuff and run migrations on the database.
So if I'm running tye, it fails to compile as files are locked.
If I'm not running tye, it has no access to database :)

I could workaround this in several ways, but would prefer having it working without workarounds, so wondering what are your thoughts.

**Comment by jkotalik** [comment] 2021-02-25 20:39
So you need your database running, and then after run `dotnet ef database update`. 

Would a precommand or post command for this after the database starts work for you? 

I think this is effectively a duplicate of https://github.com/dotnet/tye/issues/627, adding an init command.

**Closed by jkotalik** 2021-02-25 20:39 UTC
